import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import localFont from "next/font/local";

const productSans = localFont({
  src: [
    { path: "./assets/fonts/product-sans/Product Sans Regular.ttf", weight: "400", style: "normal" },
    { path: "./assets/fonts/product-sans/Product Sans Italic.ttf", weight: "400", style: "italic" },
    { path: "./assets/fonts/product-sans/Product Sans Bold.ttf", weight: "700", style: "normal" },
    { path: "./assets/fonts/product-sans/Product Sans Bold Italic.ttf", weight: "700", style: "italic" },
  ],
  variable: "--font-product-sans",
  display: "swap",
});


export const metadata: Metadata = {
  title: "D4 Community",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${productSans.className} antialiased bg-[#0E0C15]`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
