import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const josfin = Josefin_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "D4 Community",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${josfin.className} antialiased bg-[#0E0C15]`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
